### ISSUE TITLE
[💌 FEATURE REQUEST] 개발 환경에서 사용할 3rd party 클라이언트를 생성하고 관리 권한을 공유한다.

### ISSUE THREAD

**Issue by sinbom** [seeyouletter/seeyouletter-be#20]
### 멈춰! 🖐🏻 잠시 체크 들어갑니다~

- [X] [다음 페이지](https://github.com/seeyouletter/seeyouletter-be/issues)에서 중복되지 않음을 확인했어요. 🙆🏻
- [ ] 다른 분들께서 허락해주신다면, 제가 구현해보고 싶어요! 🙆🏻‍♀️

### 배경 및 설명

현재 3rd party 로그인으로 네이버/카카오를 사용할 예정입니다. 기능 구현을 위해서 클라이언트를 등록하고 관리 권한을 공유할 필요가 있습니다. 3rd party 로그인 기능을 구현을 담당하신 @JengYoung @bulmandu 님 중에서 생성하고 팀원들에게 관리 권한을 공유해주세요 🙏

### 기대결과

<개발자>는 3rd party 클라이언트를 관리할 수 있는 권한을 공유한다.

### 참고자료

- 네이버 권한 공유
<img width="1210" alt="스크린샷 2023-01-05 오전 12 14 14" src="https://user-images.githubusercontent.com/52724515/210586854-95ff55cf-ffb7-43d9-87b6-dc8188a2bcbe.png">

- 카카오 권한 공유
<img width="1293" alt="스크린샷 2023-01-05 오전 12 14 19" src="https://user-images.githubusercontent.com/52724515/210586869-8a0c051c-c67c-49bd-ae0d-540eaf5961a4.png">

**Comment by JengYoung** [comment]
네 만들겠습니다 :)
각자 관리 권한을 부여하는데 필요한 이메일 공유해주세요!

<img width="910" alt="image" src="https://user-images.githubusercontent.com/78713176/210701996-0495a5ec-3449-41ea-b8ba-3f9648d53ca4.png">

**Comment by JengYoung** [comment]
네이버의 경우 해당 스크린샷 밑에 있는 `seeyouletter`을 재사용할 수는 없을까요?!

**Comment by sinbom** [comment]
@JengYoung 재사용하셔도 상관없습니다~

아래 계정으로 권한 공유 부탁드립니다 🙇‍♂️
네이버 아이디: nmrhtn7898
카카오 메일 계정: nmrhtn7898@naver.com

**Comment by JengYoung** [comment]
그럼 재사용 가시조!
네이버는 이미 되어 있으시구 권한은 드릴 수 있는 한 모두 드리겠읍니다~~

**Comment by JengYoung** [comment]
@bulmandu 님께서도 권한 부여를 위한 계정 알려주시길 바랍니다!

**Comment by bulmandu** [comment]
네이버ID : rnalsttnn2
Kakao 계정 : rnalsttnn2@naver.com
입니드앙

**Comment by JengYoung** [comment]
다른 일정이 있어서 지금 이제야 작업을 완료했습니다 😭
모두 등록 완료했어요! @sinbom @bulmandu 
이 이슈의 목적은 모두 달성한 것 같은데 닫아도 될 것 같습니다!

<img width="960" alt="image" src="https://user-images.githubusercontent.com/78713176/210925439-974efd4a-54f5-4dbf-9334-b6098ab81f71.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/78713176/210925474-1e2bb40b-056b-49d2-8b90-584d7b8a4935.png">

**Comment by sinbom** [comment]
@JengYoung 감사합니다. 고생 많으셨어용 🙇‍♂️
