### ISSUE TITLE
[💌 FEATURE REQUEST] 카카오 Oauth2 클라이언트 동의 항목의 필수 설정을 위해서 개인 개발자 비즈 앱으로 전환한다.

### ISSUE THREAD

**Issue by sinbom** [seeyouletter/seeyouletter-be#51]
### 멈춰! 🖐🏻 잠시 체크 들어갑니다~

- [X] [다음 페이지](https://github.com/seeyouletter/seeyouletter-be/issues)에서 중복되지 않음을 확인했어요. 🙆🏻
- [ ] 다른 분들께서 허락해주신다면, 제가 구현해보고 싶어요! 🙆🏻‍♀️

## 동의 항목 설정
<img width="688" alt="image" src="https://user-images.githubusercontent.com/52724515/222881237-51215bbd-8dde-4dfc-a1df-b89a13031edd.png">

현재 카카오 Oauth2 클라이언트는 비즈 앱이 아니기 때문에 동의 항목으로 이메일을 필수 항목으로 설정할 수 없습니다.

## 비즈 앱 전환
<img width="1290" alt="스크린샷 2023-03-04 오후 3 59 29" src="https://user-images.githubusercontent.com/52724515/222881250-6507d87a-3caf-4d83-8a53-3383d44f11ca.png">

개인 개발자 비즈 앱으로 전환하면 필수 항목으로 설정할 수 있으므로 비즈 앱 전환이 필요합니다.

### 기대결과

카카오 Oauth2 클라이언트를 비즈 앱으로 전환하여 동의 항목 중 이메일을 필수 항목으로 변경할 수 있다.

**Comment by JengYoung** [comment]
아, 저번 주 내내 모든 에너지를 쏟아서 오늘 답변을 드리네요. 
죄송합니다 🙏🏻 그리고 별 말 없이 기다려주셔서 감사드려요 🙇🏻‍♂️

저번에 의견을 나눌 때 이메일 부분에서 비즈 앱 전환이 필요하다는 이야기는 들었습니다.
그리고 이제 이슈를 생성하신 걸 볼 때, 비즈 앱 전환이 필요한 시점이라고 인지하고 있습니다.

현재 비즈 앱 전환의 경우 2가지가 있는데 저희는 아직 사업자 번호는 없으므로 제가 후자의 방법으로 전환을 금일 시도해보겠습니다.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/78713176/223040021-16cc177f-e47c-4ab4-b728-7ffbc16977f2.png">

등록 완료나, 혹은 비즈 앱 전환 유무의 시점에 따라 지속적으로 해당 이슈에 말씀 드릴게요.
열심히 참여해주셔서 두 분께 감사드립니다! 🥰

**Comment by JengYoung** [comment]
현재 이메일 필수 동의를 위한 개인 비즈 앱 전환까지 완료한 상태입니다.
백엔드 측에서 정상적으로 이메일 필수 동의를 사용할 수 있는지 확인 부탁드릴게요. :) 
<img width="964" alt="image" src="https://user-images.githubusercontent.com/78713176/223041205-6b08aebd-38a6-4368-8838-8f8e7ffea821.png">

**Comment by sinbom** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/52724515/223054111-dd97f603-6d43-486c-8391-20a4dc19b1e6.png">

@JengYoung @bulmandu 
비즈앱 전환되어 이메일을 필수 동의 항목으로 변경했습니다. 감사합니다 🙇‍♂️
