### ISSUE TITLE
[🐛 BUG] 개발 환경에서의 CORS 에러를 해결한다.

### ISSUE THREAD

**Issue by sinbom** [seeyouletter/seeyouletter-be#61]
### 멈춰! 🖐🏻 잠시 체크 들어갑니다~

- [X] [다음 페이지](https://github.com/seeyouletter/seeyouletter-be/issues)에서 중복되지 않음을 확인했어요. 🙆🏻
- [X] 클라이언트 쪽 문제일 경우, [프론트엔드 레포지토리](https://github.com/seeyouletter/seeyouletter-fe)도 확인해보셨나요?
- [X] 사안을 볼 때 매우 위험해요. 빠른 수정이 필요해요! 😖

### 현재 버그는 어떤 주제인가요? (필수)

API

### 🎬 문제 재현

<img width="911" alt="cors 에러" src="https://user-images.githubusercontent.com/52724515/224948476-9be4c9ca-b8d6-4330-9ba5-0964eb919072.png">

API 서버와 다른 오리진에서 `CORS` 에러가 발생할 수 있는 요청의 케이스로 요청하는 경우 `CORS` 에러가 발생합니다.

### 버그 설명

현재 `CORS`를 허용하는 설정 파일의 오리진 목록에 오타가 기입되어 의도한 대로 작동하지 않으며 허용되어야 하는 오리진에서 `CORS` 에러가 발생합니다.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/52724515/224949190-b02d2625-7aab-46e9-b965-b32a8ee061e4.png">

단순한 오타 기입으로 인한 버그이며 `CORS` 허용 오리진들의 끝에 ,(comma) 이 기입되어 올바르게 동작하지 않았습니다.

### 예상 결과

설정 파일에 작성된 `CORS` 허용 오리진에서는 `CORS` 에러가 발생하지 않아야한다.

### 디바이스 환경

모든 웹 브라우저 환경

**Comment by sinbom** [comment]
@JengYoung 말씀해주신 에러 내용 이슈로 작성해두었습니다. 해당 이슈에서 진행상황 확인하시면 됩니다 🙇‍♂️

**Comment by JengYoung** [comment]
이슈 해결된 상황 확인했읍니다! 감사드립니다~~!
